### ISSUE TITLE
[Linux] EMDR unable to recognise cache directory

### ISSUE THREAD

**Issue by tyhawk** [gtaylor/EVE-Market-Data-Uploader#4]
I installed EMDR on my xUbuntu 12.04 box according to the instructions on the site. When trying to set up the marketlog directory, EMDR doesn't seem to be able to recognize it (I made sure there are some market log exports in there):

$ emdu_console --add-eve /home/tyhawk/PlayOnLinux\'s\ virtual\ drives/EVE_Online/drive_c/users/tyhawk/My\ Documents/EVE/logs/Marketlogs/
2013-03-24 16:16:34,449: ! No cache directories found, exiting.
$ emdu_console --add-eve "/home/tyhawk/PlayOnLinux\'s\ virtual\ drives/EVE_Online/drive_c/users/tyhawk/My\ Documents/EVE/logs/Marketlogs/"
2013-03-24 16:16:43,622: ! No cache directories found, exiting.
$ emdu_console --add-eve "/home/tyhawk/EVE/logs/Marketlogs/"
2013-03-28 18:19:22,873:  ! No cache directories found, exiting.
$ emdu_console --add-eve "/home/tyhawk/PlayOnLinux\'s\ virtual\ drives/EVE_Online/drive_c/users/tyhawk/Local\ Settings/Application\ Data/CCP/EVE/"
2013-03-28 18:45:20,797:  ! No cache directories found, exiting.

I installed pip, reverence, emdu and watchdog. Only error I ran into during install was:
Installed /usr/local/lib/python2.7/dist-packages/emdu-0.1-py2.7.egg
Processing dependencies for emdu==0.1
Searching for pyyaml
Reading http://pypi.python.org/simple/pyyaml/
Reading http://pyyaml.org/wiki/PyYAML
Best match: PyYAML 3.10
Downloading http://pyyaml.org/download/pyyaml/PyYAML-3.10.zip
Processing PyYAML-3.10.zip
Running PyYAML-3.10/setup.py -q bdist_egg --dist-dir /tmp/easy_install-PofSeD/PyYAML-3.10/egg-dist-tmp-ODfwTK
build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
compilation terminated.

libyaml is not found or a compiler error: forcing --without-libyaml
(if libyaml is installed correctly, you may need to
 specify the option --include-dirs or uncomment and
 modify the parameter include_dirs in setup.cfg)
zip_safe flag not set; analyzing archive contents...
Adding PyYAML 3.10 to easy-install.pth file

Not sure what is going on, and how to fix it. Hopefully someone else has run into this issue and was able to resolve it.

**Comment by tyhawk** [comment]
Figured it out...
emdu_console --add-eve "/home/tyhawk/PlayOnLinux's virtual drives/EVE_Online/drive_c/users/tyhawk/Local Settings/Application Data/CCP/EVE" --enable-deletion
does the trick.

Would be nice if there was a config file in which one could add 'additional' data directories, but a wrapper script does the job nicely as well.

**Comment by gtaylor** [comment]
Glad you got it working.

I thought about doing a config file, but there's so much variability between the three platforms EMDU runs on that I didn't want to get into that can of worms. A shortcut/script is indeed the best way to handle this.
